/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
  }
}
